// react/src/main.tsx
import './public-path'
import React from "react";
import ReactDOM from "react-dom";
import {RecoilRoot} from 'recoil'
import App from './App'
import {MicroAppStateActions} from './store'


function render(props) {
  const { container } = props;
  ReactDOM.render(<RecoilRoot><App></App></RecoilRoot>, container ? container.querySelector('#reactApp') :document.getElementById('reactApp'))
}

//@ts-ignore
if (!window.__POWERED_BY_QIANKUN__) {
  render({});
}

export async function bootstrap() {
  console.log('[react16] react app bootstraped')
}

export async function mount(props) {
  console.log('[react16] props from main framework', props);
  let MicroAppStateActionsInstance = MicroAppStateActions.getInstance()
  MicroAppStateActionsInstance.setMicroAppStateActions(props.onGlobalStateChange,props.setGlobalState,props.offGlobalStateChange)
  render(props)
}

export async function unmount(props) {
  const { container } = props;
  ReactDOM.unmountComponentAtNode(container?container.querySelector('#reactApp') : document.querySelector('#reactApp'))
}

// angular/src/main.ts
import './public-path';
import { enableProdMode, NgModuleRef } from '@angular/core';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';

import { AppModule } from './app/app.module';
import { environment } from './environments/environment';
import { MicroAppStateActions } from './store';

if (environment.production) {
  enableProdMode();
}

let app: void | NgModuleRef<AppModule>;
async function render() {
  app = await platformBrowserDynamic()
    .bootstrapModule(AppModule)
    .catch((err) => console.error(err));
}
if (!(window as any).__POWERED_BY_QIANKUN__) {
  render();
}

export async function bootstrap(props: Object) {
  console.log(props);
}

export async function mount(props: any) {
  const MicroAppStateInstance = MicroAppStateActions.getInstance();
  MicroAppStateInstance.setMicroAppStateActions(
    props.onGlobalStateChange,
    props.setGlobalState,
    props.offGlobalStateChange
  );
  render();
}

export async function unmount(props: Object) {
  console.log(props);
  // @ts-ignore
  app.destroy();
}
